/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mojave;

import java.util.Vector;

/**
 *
 * @author Estudiante
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form ss
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CUBO_A = new javax.swing.ButtonGroup();
        CUBO_B = new javax.swing.ButtonGroup();
        CUBO_C = new javax.swing.ButtonGroup();
        jText_dx = new javax.swing.JTextField();
        jText_cx = new javax.swing.JTextField();
        jText_bx = new javax.swing.JTextField();
        jText_by = new javax.swing.JTextField();
        jText_cy = new javax.swing.JTextField();
        jText_dy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_ax = new javax.swing.JTextField();
        jText_ay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jText_az = new javax.swing.JTextField();
        jText_cz = new javax.swing.JTextField();
        jText_bz = new javax.swing.JTextField();
        jText_dz = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1_destino = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1_cubo = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jRadio_cubo1_A = new javax.swing.JRadioButton();
        jRadio_cubo1_B = new javax.swing.JRadioButton();
        jRadio_cubo1_C = new javax.swing.JRadioButton();
        jRadio_cubo1_D = new javax.swing.JRadioButton();
        jRadio_cubo2_A = new javax.swing.JRadioButton();
        jRadio_cubo2_B = new javax.swing.JRadioButton();
        jRadio_cubo2_C = new javax.swing.JRadioButton();
        jRadio_cubo2_D = new javax.swing.JRadioButton();
        jRadio_cubo3_A = new javax.swing.JRadioButton();
        jRadio_cubo3_B = new javax.swing.JRadioButton();
        jRadio_cubo3_C = new javax.swing.JRadioButton();
        jRadio_cubo3_D = new javax.swing.JRadioButton();
        jButton_agregar_boton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_empezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText_dx.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jText_cx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_cx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_cxActionPerformed(evt);
            }
        });

        jText_bx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_bxActionPerformed(evt);
            }
        });

        jText_by.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_byActionPerformed(evt);
            }
        });

        jText_cy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_cy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_cyActionPerformed(evt);
            }
        });

        jText_dy.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("POSICION INICIAL");

        jLabel2.setText("POSICION DESEADA");

        jText_ax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_ax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_axActionPerformed(evt);
            }
        });

        jText_ay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_ay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ayActionPerformed(evt);
            }
        });

        jLabel3.setText("A");

        jLabel4.setText("B");

        jLabel5.setText("C");

        jLabel6.setText("D");

        jText_az.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_az.setText("0");
        jText_az.setEnabled(false);
        jText_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_azActionPerformed(evt);
            }
        });

        jText_cz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_cz.setText("0");
        jText_cz.setEnabled(false);
        jText_cz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_czActionPerformed(evt);
            }
        });

        jText_bz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_bz.setText("0");
        jText_bz.setEnabled(false);
        jText_bz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_bzActionPerformed(evt);
            }
        });

        jText_dz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_dz.setText("0");
        jText_dz.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jComboBox1_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox1_cubo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUBO 1", "CUBO 2", "CUBO 3" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUBO 1", "CUBO 2", "CUBO 3" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUBO 1", "CUBO 2", "CUBO 3" }));

        CUBO_A.add(jRadio_cubo1_A);
        jRadio_cubo1_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_cubo1_AActionPerformed(evt);
            }
        });

        CUBO_A.add(jRadio_cubo1_B);

        CUBO_A.add(jRadio_cubo1_C);
        jRadio_cubo1_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_cubo1_CActionPerformed(evt);
            }
        });

        CUBO_A.add(jRadio_cubo1_D);

        CUBO_B.add(jRadio_cubo2_A);
        jRadio_cubo2_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_cubo2_AActionPerformed(evt);
            }
        });

        CUBO_B.add(jRadio_cubo2_B);

        CUBO_B.add(jRadio_cubo2_C);

        CUBO_B.add(jRadio_cubo2_D);

        CUBO_C.add(jRadio_cubo3_A);
        jRadio_cubo3_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_cubo3_AActionPerformed(evt);
            }
        });

        CUBO_C.add(jRadio_cubo3_B);

        CUBO_C.add(jRadio_cubo3_C);

        CUBO_C.add(jRadio_cubo3_D);

        jButton_agregar_boton.setText("+");
        jButton_agregar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregar_botonActionPerformed(evt);
            }
        });

        jLabel9.setText("3");

        jLabel8.setText("2");

        jLabel7.setText("1");

        jLabel13.setText("CUBO N°");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)))
        );

        jLabel10.setText("Z");

        jLabel11.setText("Y");

        jLabel12.setText("X");

        jButton_empezar.setText("EMPEZAR");
        jButton_empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_empezar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText_cx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jText_bx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jText_dx, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jText_ax, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText_dy)
                                    .addComponent(jText_cy)
                                    .addComponent(jText_by, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_ay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jText_dz)
                                        .addComponent(jText_bz)
                                        .addComponent(jText_cz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jText_az, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadio_cubo1_C)
                                    .addComponent(jRadio_cubo1_D)
                                    .addComponent(jRadio_cubo1_B, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadio_cubo1_A))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_cubo2_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_cubo3_B))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_cubo2_D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_cubo3_D))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_cubo2_C)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_cubo3_C))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_cubo2_A)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_cubo3_A)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1_cubo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 89, Short.MAX_VALUE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox2, 0, 51, Short.MAX_VALUE)
                            .addComponent(jComboBox1_destino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_agregar_boton)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_agregar_boton)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1_cubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jText_dx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jText_ay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jText_by, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jText_cy, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jText_dy, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jText_ax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jText_bx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jText_cx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadio_cubo2_A)
                                        .addComponent(jRadio_cubo1_A)
                                        .addComponent(jRadio_cubo3_A))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadio_cubo1_D)
                                        .addComponent(jRadio_cubo2_D)
                                        .addComponent(jRadio_cubo3_D)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jText_az, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jRadio_cubo3_B)
                                                .addComponent(jRadio_cubo2_B, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadio_cubo1_B, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jRadio_cubo1_C)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jRadio_cubo3_C)
                                                    .addComponent(jRadio_cubo2_C))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jText_bz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jText_cz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jText_dz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95)
                .addComponent(jButton_empezar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_bxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_bxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_bxActionPerformed

    private void jText_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_byActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_byActionPerformed

    private void jText_cyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_cyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_cyActionPerformed

    private void jText_cxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_cxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_cxActionPerformed

    private void jText_axActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_axActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_axActionPerformed

    private void jText_ayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ayActionPerformed

    private void jText_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_azActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_azActionPerformed

    private void jText_czActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_czActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_czActionPerformed

    private void jText_bzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_bzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_bzActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jRadio_cubo1_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_cubo1_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_cubo1_AActionPerformed

    private void jRadio_cubo2_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_cubo2_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_cubo2_AActionPerformed

    private void jRadio_cubo3_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_cubo3_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_cubo3_AActionPerformed

    private void jButton_agregar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregar_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_agregar_botonActionPerformed

    private void jRadio_cubo1_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_cubo1_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_cubo1_CActionPerformed

    private void jButton_empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empezarActionPerformed
        // TODO add your handling code here:
        System.out.println(jText_ax.getText());
        Posicion posicionA = null;
        Posicion posicionB = null;
        Posicion posicionC = null;
        Posicion posicionD = null;
        float l1 = 3;
        float l2 = 3;
        float l3 = 3;
        float h = 2;
        
        posicionA.setTeta3(Math.acos((Math.pow(h,2)-l2*l2-l3*l3)/2*l2*l3));
    }//GEN-LAST:event_jButton_empezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CUBO_A;
    private javax.swing.ButtonGroup CUBO_B;
    private javax.swing.ButtonGroup CUBO_C;
    private javax.swing.JButton jButton_agregar_boton;
    private javax.swing.JButton jButton_empezar;
    private javax.swing.JComboBox<String> jComboBox1_cubo;
    private javax.swing.JComboBox<String> jComboBox1_destino;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio_cubo1_A;
    private javax.swing.JRadioButton jRadio_cubo1_B;
    private javax.swing.JRadioButton jRadio_cubo1_C;
    private javax.swing.JRadioButton jRadio_cubo1_D;
    private javax.swing.JRadioButton jRadio_cubo2_A;
    private javax.swing.JRadioButton jRadio_cubo2_B;
    private javax.swing.JRadioButton jRadio_cubo2_C;
    private javax.swing.JRadioButton jRadio_cubo2_D;
    private javax.swing.JRadioButton jRadio_cubo3_A;
    private javax.swing.JRadioButton jRadio_cubo3_B;
    private javax.swing.JRadioButton jRadio_cubo3_C;
    private javax.swing.JRadioButton jRadio_cubo3_D;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jText_ax;
    private javax.swing.JTextField jText_ay;
    private javax.swing.JTextField jText_az;
    private javax.swing.JTextField jText_bx;
    private javax.swing.JTextField jText_by;
    private javax.swing.JTextField jText_bz;
    private javax.swing.JTextField jText_cx;
    private javax.swing.JTextField jText_cy;
    private javax.swing.JTextField jText_cz;
    private javax.swing.JTextField jText_dx;
    private javax.swing.JTextField jText_dy;
    private javax.swing.JTextField jText_dz;
    // End of variables declaration//GEN-END:variables
}
